from .views_auth import *
from .views_pagamento import *
from .views_cadastrar import *
from .views_removerProduto import *
from .views_editarProduto import *
from .views_registrarVenda import *
from .views_vendas import *
from .views_analise import *
from .views_apiData import *
from .views_caixa import *